name: Deploy ArgoCD Applications to Multi-Region EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-primary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (Primary Region)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set to primary region

      - name: Configure kubectl for Primary Region
        run: aws eks update-kubeconfig --name eks-cluster --region us-east-1

      - name: Deploy ArgoCD Application to Primary Region
        run: kubectl apply -f manifests/argocd-app.yaml -n argocd

  deploy-secondary:
    runs-on: ubuntu-latest
    needs: deploy-primary  # Runs after primary deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (Secondary Region)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Set to secondary region

      - name: Configure kubectl for Secondary Region
        run: aws eks update-kubeconfig --name eks-cluster --region us-west-2

      - name: Deploy ArgoCD Application to Secondary Region
        run: kubectl apply -f manifests/argocd-app.yaml -n argocd
